# Generated by Django 5.2.17 on 2026-09-12 21:36

from django.db import migrations
from pgvector.django import VectorExtension



class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
